Things one can dow to prepare data for machine learning:
    
1. Rescale data.
    - Bring all attributes to same scale
    - data often rescaled into range b/w 0 and 1
2. Standardize data.
    - useful for transforming gaussian attribute to a stanard gaussian with N(0,1)
    - linear , logistic and linear discriminate analysis 
3. Normalize data.
    - rescaling each observation (row) to have a length of 1 (called a unit norm or a vector with the length of 1 in linear algebra).
    - useful in K-nearest neighbors, ANN
4. Binarize data.
    - mark values as 0 or 1. based on either values are below a threshold or above it
    - useful for probability based forecast or markings

For each pre-processing method, recipe for machine learning
remains the same:
1. split the dataset into input and output variables
2. apply a pre- processing transform to the input variable
3. summaraize the data to show the change.




In [1]:
import pandas as pd
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
df = pd.read_csv(r"./Datasets/pima-indians-diabetes.data.csv",names=names)

In [2]:
X , y = df.drop('class',axis=1) , df['class']

In [3]:
from sklearn.preprocessing import MinMaxScaler

In [4]:
scaler = MinMaxScaler(feature_range=(0,1))

rescaledX = scaler.fit_transform(X) # first apply fit and then transform

pd.np.set_printoptions(precision=3)
print("MinMaxScaler for X\n",rescaledX)

MinMaxScaler for X
 [[0.353 0.744 0.59  ... 0.501 0.234 0.483]
 [0.059 0.427 0.541 ... 0.396 0.117 0.167]
 [0.471 0.92  0.525 ... 0.347 0.254 0.183]
 ...
 [0.294 0.608 0.59  ... 0.39  0.071 0.15 ]
 [0.059 0.633 0.492 ... 0.449 0.116 0.433]
 [0.059 0.467 0.574 ... 0.453 0.101 0.033]]


In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
stan_scaler = StandardScaler().fit_transform(X)

In [7]:
print("Standard Scaler \n",stan_scaler)

Standard Scaler 
 [[ 0.64   0.848  0.15  ...  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161 ... -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 ... -1.103  0.604 -0.106]
 ...
 [ 0.343  0.003  0.15  ... -0.735 -0.685 -0.276]
 [-0.845  0.16  -0.471 ... -0.24  -0.371  1.171]
 [-0.845 -0.873  0.046 ... -0.202 -0.474 -0.871]]


In [8]:
from sklearn.preprocessing import Normalizer

In [9]:
norm = Normalizer().fit_transform(X)

In [10]:
print("Normalized \n",norm)
# rows are normalized to lenght 1

Normalized 
 [[0.034 0.828 0.403 ... 0.188 0.004 0.28 ]
 [0.008 0.716 0.556 ... 0.224 0.003 0.261]
 [0.04  0.924 0.323 ... 0.118 0.003 0.162]
 ...
 [0.027 0.651 0.388 ... 0.141 0.001 0.161]
 [0.007 0.838 0.399 ... 0.2   0.002 0.313]
 [0.008 0.736 0.554 ... 0.241 0.002 0.182]]


In [11]:
(norm[1,:]**2).sum()# ele**2 sum along each row is sum to one 
# i.e. norm is one

0.9999999999999999

In [12]:
from sklearn.preprocessing import Binarizer

In [13]:
binary = Binarizer(threshold=0).fit_transform(X)

In [14]:
print("Binarize \n",binary[:5,:])

Binarize 
 [[1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]]
